from .database import (FACE_RECOGNITION_MILVUS_DIMENSION,
                       FACE_RECOGNITION_MILVUS_COLLECTION_NAME, DEEP_FACE_MILVUS_DIMENSION,
                       DEEP_FACE_MILVUS_COLLECTION_NAME)
