import os

# Текущая активная коллекция
FACE_RECOGNITION_MILVUS_COLLECTION_NAME = "people_fr"
FACE_RECOGNITION_MILVUS_DIMENSION = 128

DEEP_FACE_MILVUS_COLLECTION_NAME = "face_embeddings"
DEEP_FACE_MILVUS_DIMENSION = 512